### ISSUE TITLE
Submit tool definitions to community repository

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/GGR-cwl#20]
https://github.com/common-workflow-language/workflows

**Comment by alexbarrera** [comment]
Some tools definitions have been submitted and some others are still only here. Unfortunately, the integration in the community Workflow repo was tedious and quite involved.

I'm closing this now, and will evaluate contributing again to the communal repo once the tools and workflows have been upgraded to v1.0 (which is necessary at this point).
