### ISSUE TITLE
Change dockerImageId to dockerPull in tool definitions

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/GGR-cwl#3]
Currently, when running a CWL tool, the dockerImage specified won't be pulled automatically.
We should:
1. Update the tool definitions to use dockerPull instead of dockerImageId
2. Include versions/tags with the image names for consistency
3. Verify that [cwl-freezer](https://github.com/Duke-GCB/cwl-freezer) looks for dockerPull
4. Evaluate writing the Dockerfile inline in the tool, rather than having in separate repository

**Comment by alexbarrera** [comment]
I have changed the dockerImageId references to dockerPull. I haven't updated the version tags of the images since some of them do not have updated versions.
